import{a as L,S as v,i as c}from"./assets/vendor-ee72e1a4.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const w=async(r,a)=>{const t=new URLSearchParams({key:"43997509-fd1501e4e0a2c27eafb2a64d5",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:15});return await L.get(`https://pixabay.com/api/?${t}`)},O=new v(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}),M=(r,a)=>{const t=r.map(({largeImageURL:o,webformatURL:e,tags:s,likes:n,views:g,comments:h,downloads:b})=>`<li name="galleryItem" class="gallery-item">
        <a class="gallery-link" href="${o}">
          <img src="${e}" alt="${s}" />
        </a>
        <div class="description">
          <p>Likes <span class="desc-span">${n}</span></p>
          <p>Views <span class="desc-span">${g}</span></p>
          <p>Comments <span class="desc-span">${h}</span></p>
          <p>Downloads <span class="desc-span">${b}</span></p>
        </div>
      </li>`).join("");a.insertAdjacentHTML("beforeend",t),O.refresh()},l=document.querySelector("section").children,m=l.getForm,y=l.loader,d=l.gallery,i=l.loadMore;let p=1,u;c.settings({progressBar:!1,timeout:4e3,resetOnHover:!0,icon:"material-icons",transitionIn:"flipInX",transitionOut:"flipOutX",position:"topRight"});const f=(r,a=1)=>{w(r,a).then(t=>{t.data.hits.length===0&&c.warning({message:"Sorry, there are no images matching your search query. Please try again!"});const o=Math.ceil(t.data.totalHits/15);if(a>o)return i.style.display="none",c.error({message:"We're sorry, but you've reached the end of search results."});i.style.display="block",M(t.data.hits,d)}).catch(t=>console.error("Error",t)).finally(()=>{m.reset(),y.style.display="none";const t=d.children.galleryItem.getBoundingClientRect();window.scrollBy({top:t.height*2,behavior:"smooth"})})},P=r=>{r.preventDefault(),d.innerHTML="",i.style.display="none",y.style.display="block",u=r.target.searchTerm.value.trim().toLowerCase(),p=1,f(u)},$=r=>{p+=1,f(u,p)};m.addEventListener("submit",P);i.addEventListener("click",$);
//# sourceMappingURL=commonHelpers.js.map
